### PR TITLE
map className to class when updating htmlAttributes

### LINKED ISSUE #204: htmlAttributes with className doesn't work with isomorphic applications
When adding `className` to `htmlAttributes` it works correct on the server, but the client adds a new `classname` attribute to the html element. And when using `class`, the server can't apply the class correctly.

### PR DESCRIPTION
**Pull request by koenpunt**
This introduces a mapping of React attributes (e.g. `className`) to html attributes (`class`). 
If other attributes have to be mapped later on they can be added easily to the `HTML_TAG_MAP` object.

should fix #204

### CODE REVIEW

**Comment by koenpunt** [comment]
Ping ✨

**Comment by cwelch5** [comment]
@koenpunt Thanks for your patience.  If you look at how we handled things like `charset` or `http-equiv` for meta tags, the API is taking in an html string that we map to React.  Could we follow this same convention and put "class": "className" in the REACT_TAG_MAP?

File: src/test/HelmetTest.js [hunk 1]
```diff
@@ -248,6 +248,22 @@ describe("Helmet", () => {
...
+                    />,
+                    container
+                );
+
+                const htmlTag = document.getElementsByTagName("html")[0];
+
+                expect(htmlTag.getAttribute("class")).to.equal("myClassName");
+                expect(htmlTag.getAttribute(HELMET_ATTRIBUTE)).to.equal("class");
+            });
+
```
Comment (cwelch5) [inline src/test/HelmetTest.js]: Also a client and server side test would be optimal.  Thank you.

**Comment by koenpunt** [comment]
REACT_TAG_MAP is for conversion the other way around, and looking up a property by its value isn't too efficient IMO.

File: src/test/HelmetTest.js (hunk 1 above)
Comment (koenpunt) [inline src/test/HelmetTest.js]: Missed the server section in the test file, will look into adding a test

**Comment by koenpunt** [comment]
Updated per request

**Comment by cwelch5** [comment]
All the other Helmet props take html keys in their objects, but htmlAttributes will be the only one that takes React keys, this could be confusing for people as the API doesn't match:

```
            <Helmet
                htmlAttributes={{"lang": "en", "amp": undefined, "className": "testclass"}}
                title="My Title"
                meta={[
                    {"charset": "utf-8"},
                    {"http-equiv": "content-type", "content": "text/html"}
                ]}
            />
```

**Comment by koenpunt** [comment]
> All the other Helmet props take html keys in their objects

You got a point there. Makes me think that these html keys actually should've been be React keys in the first place. Would you accept a PR to flip that, of course with deprecation warnings in place?

**Comment by cwelch5** [comment]
@koenpunt I'd rather not change the whole API for this one feature.  If you could switch your solution to use REACT_TAG_MAP it would be the simplest.

**Comment by cwelch5** [comment]
Having just html keys seems more declarative to me because what you are putting in is exactly what you will get out.  Because these keys are in an object and not passed directly to the component we aren't forced to use camel casing like React props. And if you are rendering on the server as a string you never have to do any conversion.

**Comment by koenpunt** [comment]
> Because these keys are in an object and not passed directly to the component we aren't forced to use camel casing like React props. 

Why is it that `generateTagsAsString` is using its own kind of templating instead of using `renderToStaticMarkup`? I know that `renderToStaticMarkup` is in `react-dom/server`, so obviously not to be (or even can't be) used on the client, but I don't believe the `toString()` of Helmet components is ought to to be used on the client?

**Comment by cwelch5** [comment]
@koenpunt excellent point, we have been meaning to convert the logic to use `renderToStaticMarkup`.  Which _would_ take React keys...  although, we'll have to test out how this affects all the different tag types and we'll have to put in logic that satisfies cases like `innerHTML` and `cssText`.

We don't use the `toString()` method on the client.  That's purely for the server.

**Comment by cwelch5** [comment]
@koenpunt Just merged a PR that is using `itemprop` as a key for title attributes.  If you could flip this to convert `class` to `className`, I can pull this in.  Thanks.

**Comment by koenpunt** [comment]
Updated, need me to squash some of these commits?

Also I expect people complaining about the inconsistency between `class`/`className`, but we'll see :)
